#
# Copyright 2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += trustbox.o
obj-y += usb_trustbox.o
obj-y += board_configuration_data.o
obj-y += eth.c
obj-$(CONFIG_FSL_PFE) += eth.o
